### ISSUE TITLE
No way to change name

### ISSUE THREAD

**Issue by Ceda-EI** [blurpy/kouchat#23]
There is **no** way to change nickname in Android ```apk```.  This can cause confusion between different users e.g. If there are 5 Android phones on Network, it will be confusing to find which device is which, especially if the network is using ```DHCP```.

**Comment by blurpy** [comment]
I see you closed the issue without any explanation, so just in case you are still wondering then please see the user guide on how to change nick name:

http://www.kouchat.net/help/user-guide/android/

**Comment by Ceda-EI** [comment]
The issue was that the color of text of that option was same as that of background and hence I got to a conclusion that there is no such option. However after I opened this issue I was scrolling through the settings and tapped on the blank space (which was the name change option) and then closed the thread .... This may be a problem with my custom rom or the app itself

**Comment by blurpy** [comment]
OK, I have never seen that before. Do you have a screenshot?

**Comment by Ceda-EI** [comment]
Here is the ![Screenshot](https://cloud.githubusercontent.com/assets/19731116/20274778/e073cac4-aabb-11e6-8b05-5f5407922be1.jpg)

**Comment by blurpy** [comment]
Huh, strange. Which rom is that, and which version of Android does it use?

**Comment by Ceda-EI** [comment]
This is `GhostRom` running `Android 6.0.1` on Lenovo K3 Note.

**Comment by Ceda-EI** [comment]
This is `GhostRom` running `Android 6.0.1` on Lenovo K3 Note.

**Comment by blurpy** [comment]
OK thanks. I'll open a new issue on the KouChat Android tracker in case others have the same problem.

**Comment by blurpy** [comment]
I have redone the settings view in version 1.1.1 on Android. I'm going to assume it works now and close the linked issue, as I have no way of testing. If you still have the issue, you can comment there.
