### ISSUE TITLE
Integrating Kouchat with my application

### ISSUE THREAD

**Issue by shlomosavransky** [blurpy/kouchat#4]
Blurpy,

I have an existing application and would like to use KouChat alongside it.

I would like to be able to communicate with the "kChat" object (see below)
    -- get list of users logged in
    -- be able to send broadcast messages from one user to all other users logged in
    -- etc...

I cannot compile this line of code (see below)
			MessageController msgController = kChat.UserInterface.getMessageController();
 
Note my code so far:

import net.usikkert.kouchat.*;

	public static KouChat kChat;

	public static void initKouChat()
	{
		String[] args = {};

		if ( ! kcInitialized )
		{
			kChat.main(args);
			MessageController msgController = kChat.UserInterface.getMessageController();
			kcInitialized = true;
		}
	}

**Comment by blurpy** [comment]
I'm not sure what you are trying to do.

You can't access anything by running `KouChat.main()`. This is the method that starts KouChat and waits forever until the user quits the application. 

Do you want to load the KouChat user interface from your code, or do you just want to use the functionality without a user interface?

**Comment by shlomosavransky** [comment]
I would like to load the KouChat interface from my code, and be able to send messages from my application code to one or more logged-in users.

________________________________

**Comment by blurpy** [comment]
You need to implement a custom "user interface" which sits between your code and the KouChat backend code. You can see the interfaces here: https://github.com/blurpy/kouchat/tree/master/src/main/java/net/usikkert/kouchat/ui

You can have a look at the console version of KouChat for a simple implementation: https://github.com/blurpy/kouchat/tree/master/src/main/java/net/usikkert/kouchat/ui/console
